### ISSUE TITLE
TimerElapsed Stats are not the same as `S`-key Stats

### ISSUE THREAD

**Issue by Chaphasilor** [KoalaBear84/OpenDirectoryDownloader#103]
**Describe the bug**

Every 30 seconds, ODD will log the current stats. They look something like this:

```
2021-08-22 14:46:11.9567  [8]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Http status codes
200: 891
404: 92
Total files: 2.161, Total estimated size: 844,21 GiB
Total directories: 983
Total HTTP requests: 987, Total HTTP traffic: 4,64 MiB
|**Url:** http://abcmoviesbd.com/Data/|||
|:-|-:|-:|
|**Date (UTC):** 2021-08-22 12:45:11|**Time:** 00:01:00||

2021-08-22 14:46:11.9723  [8]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Queue: 10.607, Queue (filesizes): 0
2021-08-22 14:46:11.9723  [8]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Remaing urls to retrieve filesize: 0
```

However, you can also access the "statistics" by pressing `s` anytime during the scan. They look something like the following:

```
Http status codes
200: 1142
404: 92
Total files: 2.888, Total estimated size: 1,09 TiB
Total directories: 1.234
Total HTTP requests: 1.238, Total HTTP traffic: 5,26 MiB
|**Url:** http://abcmoviesbd.com/Data/|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|.mp4|732|808,87 GiB|
|.mkv|276|182,87 GiB|
|.m4v|68|82,51 GiB|
|.avi|54|35,93 GiB|
|.zip|33|9,65 GiB|
|**Dirs:** 1.234 **Ext:** 20|**Total:** 0|**Total:** n/a|
|**Date (UTC):** 2021-08-22 12:45:11|**Time:** 00:01:15||

Queue: 10.371, Threads: 4
Queue (filesize): 1, Threads (filesize): 1
```

As you can see, there are multiple differences:  

- TimerElapsed stats have a timestamp and additional logging info
- TimerElapsed stats don't have the top extensions and amount of extensions
- TimerElapsed stats don't have the thread info

The structure if also a bit different, e.g. the queue section (single line vs. two separate lines)

**To Reproduce**

1. Start a scan that runs longer than 30s
2. Wait for the `TimerElapsed` stats
3. Press `s` to trigger the other statistics
4. Compare them both

**Expected behavior**

Both stats should contain the same info, preferably also formatted in the same way.  
I'd suggest using the format from the manually triggered stats for completeness' sake, logging it in one go like it's done with the manual statistics, and prefixing the whole thing with the timestamp/logging info in the line before.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0.0

**Comment by Chaphasilor** [comment]
I also noticed in the manual stats that in the markdown table, the line `|**Dirs:** 1.234 **Ext:** 20|**Total:** 0|**Total:** n/a|` should not show `0` and `n/a` for the total amount of links and total estimated size of links. Something's fishy there... 🤔

**Comment by KoalaBear84** [comment]
This is all intentional, because of performance. If you would output the full statistics every time, and you are scanning a large directory, it can take longer than a second to generate with all the extensions. For a very large directory it might even take multiple seconds, or even 10+ seconds (you will have a directory with like millions of files).

And to use multiple seconds of CPU time every 30 seconds is wasteful and slows it all down. So you get the basic fast statistics automatically, if you want the detailed you need to press `s`.

See the parameters for that:
https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/master/src/OpenDirectoryDownloader/Statistics.cs#L43

**Comment by Chaphasilor** [comment]
Okay, that makes sense.

And what about aligning the output format a bit more? E.g. always include the thread count, only prefix the first line with the logging info, etc.?

That would make everything a bit more parse-able :)

**Comment by KoalaBear84** [comment]
Yes, good idea. Didn't really knew about that difference.
