### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by itoshikisetnom** [KoalaBear84/OpenDirectoryDownloader#105]
**Describe the bug**
Can't scan any link on this site https://moedrive.org/. It's an index protected with cloudflare.

**Expected behavior**
I've scan many sites, but it doesn't work with this one. Any solution?

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - Version: [2.1.0.0]

**Comment by KoalaBear84** [comment]
That would be great, but you cannot add the cookie to ODD? Or am I missing something? 😂

**Comment by Chaphasilor** [comment]
> It was still on the list (your own ticket) 😂
 
🤦🏻‍♂️   
Guess I'll get to work then 😁

**Comment by KoalaBear84** [comment]
Merged PR #108 which includes experimental Cloudflare support.

Be sure to read the readme! It does work, but maybe when using multiple threads, or long scans, it will fail.

Let me know how it works and if you run into any problems.

If anybody have more Cloudflare protected sites to test with, let me know.

https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.2.0.1

**Comment by KoalaBear84** [comment]
@itoshikisetnom You can test it out. It's not 100% in my test, but it could work reasonable.
