### ISSUE TITLE
Support for http authentication 

### ISSUE THREAD

**Issue by a8underscore** [KoalaBear84/OpenDirectoryDownloader#107]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to download files from a personal closed directory using tools that do not support recursive downloading, although I understand this is a very specific situation, I feel like this can be beneficial to others too.

**Describe the solution you'd like**
I'd like support for http authentication, such as 
http://username:password@website.com
this is how ive seen it done in every tool ive used^

![image](https://user-images.githubusercontent.com/60801647/139541879-aac10910-7cc5-4727-a985-3915ba151953.png)
here is an example situation where a website is asking for a username/password combo, thank you

**Comment by Chaphasilor** [comment]
This is already available!

use `--username "xyz"` and `--password "xyz"` :)

More info [here](https://github.com/KoalaBear84/OpenDirectoryDownloader#usage)

**Comment by KoalaBear84** [comment]
That was fast @Chaphasilor 😂👍

**Comment by KoalaBear84** [comment]
But.. it should also work when you specify it in the URL too. Or maybe it is only for Go2Index drives. I could check that when I'm on the desktop.

**Comment by KoalaBear84** [comment]
Yes, it looks like it is only done for FTP now.

Does anyone have an example? I've tried, but I'm at the laptop on the couch, and Apache doesn't cooperate with me..

https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/4fa4b4f58d84780fe3f4e80a77019e9022c4b344/src/OpenDirectoryDownloader/FtpParser.cs#L332

**Comment by KoalaBear84** [comment]
Supported in the new release:
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.1.0.1
