### ISSUE TITLE
No URLs to save for AliceAndBooks.com

### ISSUE THREAD

**Issue by berserkwarwolf** [KoalaBear84/OpenDirectoryDownloader#111]
https://www.aliceandbooks.com/

2022-01-14 04:56:15.1216 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Curl fallback User-Agent
2022-01-14 04:56:15.3668 [11]  WARN OpenDirectoryIndexer.ProcessWebDirectoryAsync First request fails, using Chrome fallback User-Agent
2022-01-14 04:56:15.6027 [14]  WARN OpenDirectoryIndexer..ctor [P1] Error 'Response status code does not indicate success: 404 (Not Found).' retrieving on try 1 for url '/book/download-link/'. Skipping..
2022-01-14 04:56:15.6179 [14] ERROR OpenDirectoryIndexer.MoveNext Skipped processing Url: 'https://www.aliceandbooks.com/book/download-link/'

Any ideas ?

**Comment by Chaphasilor** [comment]
That doesn't look like an open directory to me, so it most likely simply isn't supported...

You could try to find an OD on the site, e.g. if it's a wordpress site there might be `/wp-data/uploads` or something, but until then you won't be able to scan this site :)

**Comment by KoalaBear84** [comment]
True. This isn't an open directory / directory listing. You need a special downloader for things like this.

**Comment by berserkwarwolf** [comment]
> True. This isn't an open directory / directory listing. You need a special downloader for things like this.

I see. Do you know of any to recommend ?

**Comment by KoalaBear84** [comment]
I guess there isn't any. I've searched for "aliceandbooks downloader" but none exists.

It it was a lot more books I would have created it myself. But because it's 'only' < 500 books it's not enough for the effort. And have too much other things on my plate :)

**Comment by berserkwarwolf** [comment]
> I guess there isn't any. I've searched for "aliceandbooks downloader" but none exists.
> 
> It it was a lot more books I would have created it myself. But because it's 'only' < 500 books it's not enough for the effort. And have too much other things on my plate :)

I can learn. But, how would I need to handle download links which are not linked to in buttons?

**Comment by KoalaBear84** [comment]
Looks like there are download links in it. A download manager will take the real filename from the server's response.

```html
<a href="https://www.aliceandbooks.com/book/download-link/521/1559" title="Download book" class="btn btn-info offset-top btn-lg download-link"><i class="fa fa-download text-primary-color"></i> Download PDF </a>
```
