### ISSUE TITLE
Crash when not specifying a protocol

### ISSUE THREAD

**Issue by 4censord** [KoalaBear84/OpenDirectoryDownloader#112]
**Describe the bug**

When only specifying an ip address without a protocoll, odd crashes  with
```shell
Started with PID 24241
URL specified: 127.0.0.1
URL fixed    : http://127.0.0.1/
Unhandled exception. System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at OpenDirectoryDownloader.Program.Main(String[] args) in [REMOVED_PATH]/OpenDirectoryDownloader/src/OpenDirectoryDownloader/Program.cs:line 124
   at OpenDirectoryDownloader.Program.<Main>(String[] args)
fish: Job 1, './bin/OpenDirectoryDownloader -…' terminated by signal SIGABRT (Abort)
```

**To Reproduce**
`OpenDirectoryDownloader --url 127.0.0.1`

**Expected behavior**

No crash

**Desktop (please complete the following information):**
 - OS: linux
 - Version: current master: 5d0765ff

**Comment by 4censord** [comment]
More specific it crashes in this section:

https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/5d0765ffcebb9a01852a5dac26803f17af4253af/src/OpenDirectoryDownloader/Program.cs#L122-L130

It tries to extract a username and password from the provided url
(127.0.0.1), and not the sanitized url that is created here

https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/5d0765ffcebb9a01852a5dac26803f17af4253af/src/OpenDirectoryDownloader/Program.cs#L105-L114

**Comment by Chaphasilor** [comment]
Hmm, it looks likes this function isn't returning `false` when it should be:

https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/5d0765ffcebb9a01852a5dac26803f17af4253af/src/OpenDirectoryDownloader/Library.cs#L349-L364

The issue appeared after v2.1.0.0, I'm guessing right after it with this commit: https://github.com/KoalaBear84/OpenDirectoryDownloader/commit/5f08d02d85d5f983888047a465e6394f951affdb#diff-28bad5a72dee380228016222e2442b1cc7bbd86b59e16653038c9b8fdce2b2be

**Comment by 4censord** [comment]
I think the crash happens in the call to `new Uri(url)`, an not the `GetUriCredentials` function.

```c#
Uri uri = new Uri(url); // <= crash here
if (Library.GetUriCredentials(uri, out string username, out string password))
{
	Console.WriteLine($"Using username '{username}' and password '{password}'");
	openDirectoryIndexerSettings.Username = username;
	openDirectoryIndexerSettings.Password = password;
}
```

**Comment by KoalaBear84** [comment]
Thanks, I see I was not using the 'fixed' url. 👍

**Comment by KoalaBear84** [comment]
Released: https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.3.0.1
