### ISSUE TITLE
No folder for LogArchives on systems with `/` as path seperator

### ISSUE THREAD

**Issue by 4censord** [KoalaBear84/OpenDirectoryDownloader#116]
**Describe the bug**

On systems not using `\` (backslash) as the path seperator old logs are named `LogArchives\OpenDirectoryDownloader.01.log`

**To Reproduce**

* Be on a system that uses `/` (forwardslash) as the path seperator (Linux *BSD Mac)

* Use odd enough to rotate the log
* See the old logs named `LogArchives\OpenDirectoryDownloader.01.log`

**Expected behavior**

The old logs are placed it a Folder named `LogArchives`

**Desktop (please complete the following information):**
 - OS: Linux 5.18.5-arch1-1 
 - Version: `2.3.1.0`

**Comment by KoalaBear84** [comment]
That's a good find 👍

**Comment by KoalaBear84** [comment]
Hopefully fixed with: https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.3.1.1

**Comment by 4censord** [comment]
You are very much faster than me. I just finished researching how to fix that and you already released the fix.

**Comment by KoalaBear84** [comment]
Let me know it is fixed with this.
