### ISSUE TITLE
Add mounting support

### ISSUE THREAD

**Issue by upintheairsheep** [KoalaBear84/OpenDirectoryDownloader#126]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Please add support for mounting Open Directories via FUSE, not downloading them, but accessing them on demand.

**Comment by Chaphasilor** [comment]
ODD doesn't download Open Directories at all, the name is a bit confusing :)

**Comment by KoalaBear84** [comment]
I don't have any experience with this, and I also think it is not cross platform.

If anybody knows, submit a PR.

**Comment by 9001** [comment]
You might be able to use [rclone](https://rclone.org/) for this -- it understands a handful of OD servers, and is able to mount them on windows and linux. You won't get the wide support that ODD provides but it's better than nothing :>

Adding this to ODD would definitely be a huge effort! It's possible that either dokany or winfsp could help making it easier to add windows support, but I bet there'd be all sorts of crazy cornercases...

**Comment by upintheairsheep** [comment]
I know, but rClone supports less.

**Comment by KoalaBear84** [comment]
Sorry, will never happen for me. It would also not be easily supported I think even if somebody can do the mounting part.
