### ISSUE TITLE
Actual OD Downloading support

### ISSUE THREAD

**Issue by upintheairsheep** [KoalaBear84/OpenDirectoryDownloader#127]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
Please add a flag to actually download open directories. The flag should simply use wget <s>or curl</s> on every file it can, creating directories whenever it needs to, eliminating the need for a second command.

**Comment by KoalaBear84** [comment]
Something like this always was the initial idea, but that is not going to happen in this repo / tool.

And also will not add this feature, BUT there is a good workaround which you can use right now 😇

`OpenDirectoryDownloader.exe --output-file urls.txt && wget -x -i urls.txt`
