### ISSUE TITLE
Continous Downloading/Crawling depending on Timestamp

### ISSUE THREAD

**Issue by leex279** [KoalaBear84/OpenDirectoryDownloader#129]
I´ve got the usecase that I need to download a lot (millions) of files every month from an URL and I have no solution to do that on a continous way. Therefore it would be very nice, if you could provide a feature to remember where it stopped last (maybe depending on the "last modified" time, so I could start the iteration from that point and not from beginning, whats takes me a long time and also stresses the web-server.

**Comment by KoalaBear84** [comment]
I think there isn't a good way to do this in a generic way. There also isn't a way to load a previous scan and continue in any way.

A specific crawler / script is probably needed.
