### ISSUE TITLE
No Values Being Displayed

### ISSUE THREAD

**Issue by nevadarain** [KoalaBear84/OpenDirectoryDownloader#13]
Im using windows 10,  I installed 3.0 preview 5 and also Visual Studio 2019 preview.  Everything seems to work except I'm not getting any values displayed.   Please see the output below.  Any help will be greatly appreciated.

Started
URL specified: http://www.joellagace.com/Converted%20books/
URL fixed: http://www.joellagace.com/Converted%20books/
Started indexing!
****************************************************************************
****************************************************************************
***  Press I for info (this)                                             ***
***  Press S for statistics                                              ***
***  Press T for thread info                                          ***
***  Press J for Save JSON                                           ***
***                                                                              ***
***  Press ESC to EXIT                                                  ***
****************************************************************************
****************************************************************************
Finshed indexing
Saving URL list to file...
Saved URL list to file: http___www.joellagace.com_Converted%20books_.txt
2019-06-07 21:58:53.3492 [20]  WARN <<StartIndexingAsync>b__0>d.MoveNext Only a speedtest for HTTP(S)
Http status codes
200: 10
Total files: 0, Total estimated size:  B
Total directories: 10
Total HTTP requests: 10, Total HTTP traffic: 74.49 kB
|**Url:** [http://www.joellagace.com/Converted%20bo...](http://www.joellagace.com/Converted%20books/)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 10 **Ext:** 0|**Total:** 0|**Total:**  B|
|**Date:** 6/8/2019 2:58:49 AM +00:00|**Time:** 00:00:03||

Finished indexing!

**Comment by KoalaBear84** [comment]
Sorry for the late response. You are right. It looks like this directory listing format is not (yet) supported. I will try to look into it asap.. :)

**Comment by KoalaBear84** [comment]
Noo.. The site is now offline. I cannot check if it is fixed with some other improvements lately.

Please open it again if it is responding again, or create a new ticket when you found another one.
