### ISSUE TITLE
Copyparty `--force-js` support

### ISSUE THREAD

**Issue by KoalaBear84** [KoalaBear84/OpenDirectoryDownloader#130]
Add `--force-js` support to copyparty.

See https://github.com/KoalaBear84/OpenDirectoryDownloader/pull/128#issuecomment-1384488822 for more info

**Comment by KoalaBear84** [comment]
Released:
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.8.0.1

Please check if it is working at your end @9001 😇

**Comment by 9001** [comment]
Dude nice! It even does the undecodable filename at https://cd.ocv.me/b/d3/.dragons/, impressive :>

good work :+1: :+1:

**Comment by KoalaBear84** [comment]
Haha, thanks, great! 👍
