### ISSUE TITLE
Unsupported site

### ISSUE THREAD

**Issue by upintheairsheep** [KoalaBear84/OpenDirectoryDownloader#131]
**Describe the bug**

https://kirbfeels.cc/ This site is currently unsupported by the downloader

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.0.0.0]

**Comment by KoalaBear84** [comment]
Ahh, I missed this one, it was in my inbox, but it was already marked as read too.

Yes.. This one isn't 'good', the url you are using doesn't indeed work, and uses a broken iframe tag too. Iframes are not supported, and also doesn't really make sense. The only thing I might be able to do it show the iframe URLs in the output so the user can try these.

![image](https://user-images.githubusercontent.com/5886900/216166169-509256b6-0cbe-473b-ad73-1d325b550210.png)

Using https://kirbfeels.cc/library/ will work:

|**Url:** [https://kirbfeels.cc/library/](https://kirbfeels.cc/library/)||[Urls file](https://pixeldrain.com/u/n6Q8Zwnp)|
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|.zip|48|7.61 GiB|
|.mp4|159|7.04 GiB|
|.mp3|1,479|6.67 GiB|
|.7z|9|5.15 GiB|
|.flac|239|3.59 GiB|
|**Dirs:** 297 **Ext:** 93|**Total:** 3,837|**Total:** 43.2 GiB|
|**Date (UTC):** 2023-02-01 21:23:35|**Time:** 00:00:14|**Speed:** 2.47 MB/s (19.7 mbit)|

Future version will show this:

2023-02-01 22:41:04.232 [WRN] No directories and files found on https://kirbfeels.cc/, but did find <iframe> tag(s), you could try this url(s):
https://kirbfeels.cc/library/

**Comment by KoalaBear84** [comment]
Because it's already implemented I see, I'm closing it 😅
