### ISSUE TITLE
cant open in colab, giving error

### ISSUE THREAD

**Issue by askfriends** [KoalaBear84/OpenDirectoryDownloader#136]
**Describe the bug**
when importing or opening in colab, it says file invalid
**To Reproduce**
1. Download the ipynb file and open in colab
2. you will see file invalid error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.0.0.0]

**Comment by KoalaBear84** [comment]
Hi @askfriends 

Sorry for this very late reply.. I've ran it and it working without any issues.

Did you follow the steps here?
https://github.com/KoalaBear84/OpenDirectoryDownloader#google-colab--jupyter-notebook

![image](https://github.com/KoalaBear84/OpenDirectoryDownloader/assets/5886900/cc0bec50-91b6-4fcc-833a-05615a12f225)

![image](https://github.com/KoalaBear84/OpenDirectoryDownloader/assets/5886900/e4c6a6a1-6986-4c5d-97f8-62e01ecf8748)
