### ISSUE TITLE
How to Paste URLs into the program.

### ISSUE THREAD

**Issue by RetroJimmyX** [KoalaBear84/OpenDirectoryDownloader#139]
I exectued the self-contained Windows application but cannot seem to paste URLs when prompted ("Which URL do you want to index?"). I've tried using the standard CTRL+V, right-click, middle-click but none seem to work. I can't find any instructions on usage that covers this - please advise, thank you.

**Comment by KoalaBear84** [comment]
I have never heard of anything like this.

CTRL + V and Right click should work like they do normally.

Which Windows version and terminal do you use? Have your tried rebooting?

Can't think of any it would work.

Alternative is using the -u of --url and fill it in like that.

**Comment by RetroJimmyX** [comment]
Ah man, I don't why it works now, I didn't even restart the PC. Thanks for prompt reply; and sorry to bother.

**Comment by RetroJimmyX** [comment]
User error.

**Comment by KoalaBear84** [comment]
No problem. Glad it works 👍
