### ISSUE TITLE
Support multiple URL to crawl

### ISSUE THREAD

**Issue by maaaaz** [KoalaBear84/OpenDirectoryDownloader#143]
Hello there,

Currently ODD only allow 1 URL at the time with the `-u` option.
However, in multiple situations, a user can need to crawl different multiple URLs (just as the `-i` option in `wget`).

Can you add this feature allowing to specify a list of URLs to crawl with ODD ?

Cheers !

**Comment by KoalaBear84** [comment]
Hi. This won't be supported. It's not easy to implement, and it is easy to do in almost every command line.

On Windows it's possible with a bach file (example) and with a file (urls.txt):
```batch
for /F "tokens=*" %%A in (urls.txt) do OpenDirectoryDownloader.exe --json --upload-urls --speedtest --quit --url %%A
```

Or by piping the command's together:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipelines?view=powershell-7.4
https://www.geeksforgeeks.org/piping-in-unix-or-linux/
https://lucadistasioengineering.com/wincmd-novice/04-pipefilter/index.html
