### ISSUE TITLE
ODD returns status code '1' even if index is successful

### ISSUE THREAD

**Issue by Bad3r** [KoalaBear84/OpenDirectoryDownloader#144]
**Describe the bug**
When running ODD with -q or --quite it always exists with status code 1 which indicates an error. This happens even if the scan is 'successful' and compeleted.

**To Reproduce**
1. run ODD and specify -q
2. once done get the last command output status. On linux and I think mac its `echo $?`

Example test case:
```powershell
❯ ./OpenDirectoryDownloader --url "https://unsigned.sh" -q --fast-scan; echo "Status code: $?"
Started with PID 151240
URL specified: https://unsigned.sh
URL fixed    : https://unsigned.sh/
Started indexing!
...
Finshed indexing
|**Url:** [https://unsigned.sh/](https://unsigned.sh/)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:** n/a|
|**Date (UTC):** 2024-12-12 09:39:25|**Time:** 00:00:01||
...

No URLs to save
...
200: 1
Total files: 0, Total estimated size: n/a
Total directories: 1
Total HTTP requests: 1, Total HTTP traffic: 3.04 kiB
|**Url:** [https://unsigned.sh/](https://unsigned.sh/)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:** n/a|
|**Date (UTC):** 2024-12-12 09:39:25|**Time:** 00:00:01||
...
Finished indexing!
Exiting...
Status code: 1
```

I own the URL so you are welcome to use it for testing as well. Note that its behind CF. 

**Expected behavior**
The status code should be 0 if the target is reachable and scan completed 

**Desktop (please complete the following information):**
 - OS: Arch Linux, btw
 - Version: 6.12.4
 - built with: ❯ dotnet --version 8.0.110

**Comment by KoalaBear84** [comment]
Hi.

I see.. Oops! I never use status codes, but indeed, it should be 0 if there are no errors.

It will be fixed in the next version. Sadly I didn't manage to fix the build pipeline yet.. Need to try it a 3th time.

**Comment by Bad3r** [comment]
> Hi.
> 
> I see.. Oops! I never use status codes, but indeed, it should be 0 if there are no errors.
> 
> It will be fixed in the next version. Sadly I didn't manage to fix the build pipeline yet.. Need to try it a 3rd time.

Awesome thank you for the quick response and quick fix. It makes using ODD in script must easier to work with. 

I appreciate all your hard work. I love this tool. Thank you!

**Comment by KoalaBear84** [comment]
It has been released a couple of hours ago.
