### ISSUE TITLE
The ipynb don't work anymore

### ISSUE THREAD

**Issue by VoXaN24** [KoalaBear84/OpenDirectoryDownloader#145]
**Describe the bug**
The latest release don't have the compiled file, so Google Colab can't use it

**To Reproduce**
1. Open the ipynb on Google Colab or Jupytr

**Comment by KoalaBear84** [comment]
Hi @VoXaN24 

Sorry for the late reply. I know why.. It's the same reason why there aren't new versions yet.. The GitHub Actions which creates the builds is not working.

You can fix it by using the latest version which has assets, which is v3.1.0.1

Open the ipynb and change the following line:
`LatestVersionUrl=!curl https://api.github.com/repos/KoalaBear84/OpenDirectoryDownloader/releases/latest -s | jq -r '.assets[] | select(.name | endswith("linux-x64-self-contained.zip")) | .browser_download_url | tostring'`
to
`LatestVersionUrl=!curl https://api.github.com/repos/KoalaBear84/OpenDirectoryDownloader/releases/tags/v3.1.0.1 -s | jq -r '.assets[] | select(.name | endswith("linux-x64-self-contained.zip")) | .browser_download_url | tostring'`

**Comment by KoalaBear84** [comment]
Finally! The builds / releases are working again! 😅

So.. you probably don't have to do the above anymore. 😇
