### ISSUE TITLE
Google Colab Notebook

### ISSUE THREAD

**Issue by Al-poth** [KoalaBear84/OpenDirectoryDownloader#17]
It would be more helpful, if there is a google colab notebook for  this. hope you will consider this.

**Comment by KoalaBear84** [comment]
What do you mean with Google Colab Notebook. And why?

**Comment by KoalaBear84** [comment]
@Al-poth Can you explain why you created this issue?

**Comment by KoalaBear84** [comment]
Please, what do you mean with this?
