### ISSUE TITLE
[json] - getting error while saving as json

### ISSUE THREAD

**Issue by alx-xlx** [KoalaBear84/OpenDirectoryDownloader#21]
**Describe the bug**
I was getting error while saving the **.json** using **J** key, I found out that **Scans** Folder was not created at this location `C:\Users\Administrator\AppData\Local\Temp\2\.net\OpenDirectoryDownloader\bygfrh2s.ae1,` so i had to fix it by adding it manually.

![VpmYM3ikjv](https://user-images.githubusercontent.com/42188371/79077955-9fb4ae80-7d22-11ea-802b-7d4a1bfe895e.gif)

**To Reproduce**
1. Go to 'OpenDirectoryIndexer.exe -u https://gooddebate.org/sin/mirror/library/'
2. Click on 'J'
3. Scroll down

**Expected behavior**
I expected the tool to automatically save the **.json** file without any manual setup

**Screenshots**
Error
![mstsc_lCikS9nXPT](https://user-images.githubusercontent.com/42188371/79077484-bdccdf80-7d1f-11ea-9325-68115b5e069c.png)

**Desktop (please complete the following information):**
 - OS: [Windows Server 2019]
 - Version [17763]

**Comment by KoalaBear84** [comment]
Which version did you use? I guess you used 1.2.0.0?

I still need to fix the build/releases system and get a new build out..

**Comment by alx-xlx** [comment]
yes I used v1.2.0.0
ok

**Comment by KoalaBear84** [comment]
Could you https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/latest ?

**Comment by KoalaBear84** [comment]
Latest check, if no reply I will close it.
