### ISSUE TITLE
Suggestion for the read me file

### ISSUE THREAD

**Issue by oneplusson** [KoalaBear84/OpenDirectoryDownloader#23]
I'm trying to use this tool but i done see any .exe file. I'm i supposed to compile the files by myself? I haven't done anything similar earlier but i would appreciate if you had those instructions in the readme file.

**Comment by KoalaBear84** [comment]
Somewhat correct. If you want the newest version you currently need to build it yourself. If you are running Windows, then 1.0.0.0 in the releases page is OK.

If you want to run the newest, please download or clone the repository, install the SDK and run `dotnet run`.

SDK (See "Build apps - SDK" part):
https://dotnet.microsoft.com/download/dotnet-core/3.1

I'm not sure if it needs to run in the root, of in the first directory (OpenDirectoryDownloader).

**Comment by oneplusson** [comment]
i somehow managed to enter the the "OpenDirectoryDownloader" folder with powershell in windows 10, the folder was in the folder "opendirectorydownloader-master". i cannot find  1.0.0.0 release?

however, attached is two print of how it looks, is it supposed to look like that?
<img width="811" alt="after running the the command" src="https://user-images.githubusercontent.com/63904986/79639858-81b9d480-818e-11ea-998d-2ff1e8efb8bb.PNG">
<img width="412" alt="powershell1" src="https://user-images.githubusercontent.com/63904986/79639859-82eb0180-818e-11ea-8a97-4426ab6ac814.PNG">

**Comment by oneplusson** [comment]
Now i tried to run the .
<img width="782" alt="redtext" src="https://user-images.githubusercontent.com/63904986/79640133-2a1c6880-8190-11ea-992b-7067d731a630.PNG">
exe file, i pasted my link of the open directory and it just throws out a bunch of red text combined with yellow text. Is it supposed to work in this way?

I appreciate your help and you engagement.

**Comment by KoalaBear84** [comment]
I've tried for 2 hours to get a new build through GitHub, but failed until now.

Yes, that is how it is supposed to work/look. For those errors I have created a better 'failsafe' mechanism, and testing it last week. This will try it a little more times and handles some error states faster/better.

Great to see you succeeded.

**Comment by oneplusson** [comment]
Thank you mister!

**Comment by KoalaBear84** [comment]
I'll close this now, finally got the builds working with some external help :)

Also made the build and run part a little more general.

For the new release:
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.4.0.0
