### ISSUE TITLE
Error when there is no Console / Console Input attached

### ISSUE THREAD

**Issue by dunklesToast** [KoalaBear84/OpenDirectoryDownloader#24]
**Describe the bug**
I am using this tool in another script and I call it as a childProcess. Therefore, it has no Console attached to it which causes the script to throw a lot of errors.

**To Reproduce**
```js
const childProcess = require('child_process');
const response = childProcess.spawnSync('dotnet', ['src/netcoreapp3.1/OpenDirectoryDownloader.dll', '--url=http://someurl.tld', '-q', '-j']);
console.log(response.output.toString())
```

**Expected behavior**
When there is no console attached to the script it should not print anything out.

**Console Output**
```ERROR Command.ProcessConsoleInput Error processing action System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.```

**Desktop (please complete the following information):**
 - OS: macOS Catalina 
 - Version: 10.15.3 (19D76)
 - node: v10.17.0

**Comment by KoalaBear84** [comment]
Haha. I just got this last week myself.

If you replace the Command.cs with this one, you can use it. It's not fully ready to be committed yet, but will be later.

https://gist.github.com/KoalaBear84/449bb182b954322a0af5813f504ea16b

**Comment by dunklesToast** [comment]
Ok thanks! Leave the issue open until it's fixed in master?

**Comment by KoalaBear84** [comment]
Yes! 😁

**Comment by dunklesToast** [comment]
So I actually just tried that fix and have 6 of these errors:
` Command.cs(75, 37): [CS0120] An object reference is required for the non-static field, method, or property 'OpenDirectoryIndexer.Session'`.
Lines:
- 75:37
- 77:82
- 112:37
- 114:82
- 145:41
- 176:58

**Comment by KoalaBear84** [comment]
Indeed, that is the reason it is not yet committed. I think you can also do just "session", as it is/was a parameter.

I want to commit it soon, but first have to get it untangled 😇 (and first had to fix the releases problem which is fixed now)
