### ISSUE TITLE
Support FTPS URLs

### ISSUE THREAD

**Issue by Jan02** [KoalaBear84/OpenDirectoryDownloader#27]
**Is your feature request related to a problem? Please describe.**
need to index ftps

**Describe the solution you'd like**
ftps that works

**Comment by KoalaBear84** [comment]
Can you send me an example of one, so I can test?

I also tried something for this last week, but haven't found a reliable way. FTP is a horrible thing 😂

**Comment by Jan02** [comment]
ok I sent you the info by email.

**Comment by KoalaBear84** [comment]
Received and replied. Will try to look at it ASAP. Do have some problems that I changed a lot of FTP related things, but not ready for committing that yet.

**Comment by KoalaBear84** [comment]
That took a lot longer than expected. I started shortly after this, but got stuck in the encryptions etc. And then more time passed :)

It only support 'basic' / user/pass authentication, no certificates, and that will never probably never added (then you are in serious trouble :P).

Try it and let me know!
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.5.1.1
