### ISSUE TITLE
[Request] Make it Colab or heroku compatible

### ISSUE THREAD

**Issue by askfriends** [KoalaBear84/OpenDirectoryDownloader#31]
hi..
this is very helpful project special for downloading google index websites.
Can you plz make it google colab compatible? so that we can run it in colab?

also it would be nice if you make it compatible with heroku, so that we can create an web app on heroku.

**Comment by KoalaBear84** [comment]
I think that is technically not that possible.

It already works for the normal indexes:

https://www.reddit.com/r/opendirectories/comments/hhjtpf/od_indexer_in_colab/

**Comment by askfriends** [comment]
Thanks for the

> I think that is technically not that possible.
> 
> It already works for the normal indexes:
> 
> https://www.reddit.com/r/opendirectories/comments/hhjtpf/od_indexer_in_colab/
> 
> And I have no knowledge about Heroku.

Thanks for the quick reply, i saw that link and downloaded  .ipynb file. But there is no any option to use it to download from google index sites. I think its for downloading normal index websites. Will you look into that file and made necessary changes to make it work with google index?
it would be nice if you add that link in your readme and instructions how to use it.

**Comment by KoalaBear84** [comment]
For Google Drive you need an extra file, which you might copy to Colab, not sure how that works.

The GoIndex (Google Drive alternatives) ones would already work.

**Comment by askfriends** [comment]
> For Google Drive you need an extra file, which you might copy to Colab, not sure how that works.
> 
> The GoIndex (Google Drive alternatives) ones would already work.

I am getting this error, it doesnt not work. OR am i doing anything wrong?
and btw where do i find crawled links file?
![asas](https://user-images.githubusercontent.com/2517219/90268270-324f9080-de70-11ea-9af2-7dedcf47b383.png)

**Comment by KoalaBear84** [comment]
You did it correctly. Looks like this has another format or implementation, will check it.

**Comment by KoalaBear84** [comment]
I've added support and created a new release for it. If you use this new release in it, it should work:

https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.5.2.0

**Comment by askfriends** [comment]
> I've added support and created a new release for it. If you use this new release in it, it should work:
> 
> https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.5.2.0

I'm here for colab script of this script to use it more efficiently, so please make official colab script.

**Comment by KoalaBear84** [comment]
I have no knowledge of it.

**Comment by KoalaBear84** [comment]
Someone with experience could provide some guidance on this. Can this be added to this repository as a file? Or how do you work with this?

**Comment by Chaphasilor** [comment]
I don't know about Google Collab, but adding support for Heroku is only partially possible.

You can create Heroku addons than can be installed alongside your server (meaning ODD could be downloaded and added to the `PATH` variable), but you don't have any kind of console access, which means you'd need a wrapping server.

Another way to use the binary is by using [my Node.js wrapper](https://github.com/Chaphasilor/open-directory-downloader), which automatically downloads the latest binary for you.

I've actually done just that and created https://open-directory-downloader.herokuapp.com (URL subject to change), which runs on Heroko, uses my wrapper to handle the binary and has source code available [here](https://github.com/Chaphasilor/OpenDirectoryDownloader-gui).   
So in case someone wants to set up their own instance (for whatever reason), they can easily do it :)

**Comment by Kinkguy** [comment]
Can i get the colab file

**Comment by Kinkguy** [comment]
It's expired in reddit

**Comment by KoalaBear84** [comment]
I didn't knew I still had it somewhere on my computer, as I'm not the poster of it.

[ODindexer.zip](https://github.com/KoalaBear84/OpenDirectoryDownloader/files/6714077/ODindexer.zip)

**Comment by Kinkguy** [comment]
Thank u so much @KoalaBear84 didn't expect such quick reply

**Comment by KoalaBear84** [comment]
Official support is now added:

https://github.com/KoalaBear84/OpenDirectoryDownloader/#google-colab--jupyter-notebook

**Comment by KoalaBear84** [comment]
Thanks to @Chaphasilor it is greatly improved!
