### ISSUE TITLE
Exit when all jobs are finished

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#32]
**Is your feature request related to a problem? Please describe.**
I'm thinking about calling OpenDirectoryDownloader from another application. The fact that it waits for the ESC keystroke makes this a bit harder than it could be.

**Describe the solution you'd like**

A command-line option that makes the program exit automatically when all jobs are finished.

**Comment by KoalaBear84** [comment]
Hey McOfficer.

Use `-q` or `--quit` and you should be fine 😁

**Comment by MCOfficer** [comment]
Oh, i see. Perhaps the description "Do not wait after scanning" is bit ambiguous - at least, i didn't understand it. Thanks!

**Comment by KoalaBear84** [comment]
Yes, if you have a better description, let me know and I'll change it.

**Comment by MCOfficer** [comment]
hm. 

- Exit after scanning
- Do not wait for user input after scanning

?

**Comment by KoalaBear84** [comment]
Thanks, changed it to a combination of it.

_Quit after scanning (No "Press a key")_
