### ISSUE TITLE
How can I run this on Mac?

### ISSUE THREAD

**Issue by sinepgnol** [KoalaBear84/OpenDirectoryDownloader#35]
How can I run this on Mac?

**Comment by KoalaBear84** [comment]
See https://github.com/KoalaBear84/OpenDirectoryDownloader/releases for the binaries

**Comment by sinepgnol** [comment]
Thank you Koala, I have already seen that and downloaded the Mac binaries, but what should I do with them afterwards? How do I run it?

**Comment by KoalaBear84** [comment]
I have no idea, I don't have any experience with macs. You should be able to do something like "opendirectorydownloader" and run it. 😯

**Comment by sinepgnol** [comment]
Got it, had to make OpenDirectoryDownloader an executable by running `chmod 755 OpenDirectoryDownloader`

**Comment by KoalaBear84** [comment]
Hmm, how does this go normally when downloading something? I guess normally you don't need this.

If anybody sees this, please comment! Or any .NET (Core) developer.
