### ISSUE TITLE
Uploads urls file - parameter -l - What does this function serve for?

### ISSUE THREAD

**Issue by sinepgnol** [KoalaBear84/OpenDirectoryDownloader#36]
I really would like to know.

**Comment by KoalaBear84** [comment]
It uploads the URLs to gofile.io or when failed to uploadfiles.io and will add it to the Reddit stats.

See:
![image](https://user-images.githubusercontent.com/5886900/95167475-0685c280-07b0-11eb-9050-b921fddc78bc.png)

**Comment by sinepgnol** [comment]
Thank you!
