### ISSUE TITLE
Find most top-level directory

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#37]
**Is your feature request related to a problem? Please describe.**
I'll admit this is one for automation. When given a link, an automated system has no way of knowing wether it's the Opendirectory root or merely a subfolder. The best (most reliable) way to find that would be to look for a "parent folder" (`../`) link. And what better program to do that than the one that's already parsing all kinds of OD formats?

**Describe the solution you'd like**
When given a specific flag, the program won't scan the current folder, but the highest-level folder it can find.

Alternatively, when given a specific flag, output the highest-level folder it can find without scanning it.

**Comment by KoalaBear84** [comment]
Already thought about this myself long time ago. The problem is that it must be given a Open Directory kinda link, else it will fallback to link scanning which will try it's best to make sense of it. But this will result in possibly NOT an open directory and garbage results.

Maybe it is possible to check if the given URL is present in the upper level directory as a safety check.

**Comment by MCOfficer** [comment]
> Maybe it is possible to check if the given URL is present in the upper level directory as a safety check.

that would also be fallible. see for example https://endlesssky.mcofficer.me/, which links to my asset directory but is not an OD.

I think the safest option would be to only proceed searching if the format is known.

**Comment by KoalaBear84** [comment]
Hmm, looks like I never replied. It is not possible to really see if it is an open directory. It will probably always return any results on many pages, but then it will have used the 'links' fallback which just indexes all links.

While that works nicely for open directories, it will not when it's a subdirectory of a regular website. So eventually it will reach the 'homepage' and it will screw up.

So.. It's not that easy / reliable.

**Comment by Chaphasilor** [comment]
Just brainstorming ideas here:

- How about we check if a possible "parent directory" has certain properties? For example, most OD listings don't have any large images, certain texts, use frameworks, etc. We could use these criteria to confirm if a link is a directory.
- Checking if there is a link back to the child directory could be use to sort out non-OD parent directories. Basically any OD will link it's subfolders, but if there's no link, it's most likely no OD. If there *is* a link however, we're not any smarter...

iirc, @Krazybug also had an algorithm for it as described [here](https://github.com/Chaphasilor/odcrawler-scanner/issues/5#issuecomment-748048871)

**Comment by Chaphasilor** [comment]
Another idea: if ODD can scan the OD, the format is known. We could then look for parent directory links, and check to see if the format of the parent directory is the same.

If the format doesn't match, or the OD can only be scanned naively using URL parsing, no parent directory can be found, so we scan the provided directory.

This should work well for cases where we have a link to subdirectory of an OD in a known format, right?

**Comment by KoalaBear84** [comment]
It's still very complicated. You also have to exclude the links fallback, that is like the 'wildcard'.

**Comment by Chaphasilor** [comment]
> It's still very complicated. You also have to exclude the links fallback, that is like the 'wildcard'.

Yeah that's what I meant with "naively". Only the "explicit" formats are supported for finding the OD root. It won't work for all ODs, but it's a best-effort solution, don't you think?
