### ISSUE TITLE
I Cannot Scan this OD "https://chromedriver.storage.googleapis.com/index.html"

### ISSUE THREAD

**Issue by M-Sethupathy** [KoalaBear84/OpenDirectoryDownloader#41]
Link : https://chromedriver.storage.googleapis.com/index.html

This site(Selenium Chrome Driver Download Page) looks like Standard OD:

But it shows something like this:

|**Url:** [https://chromedriver.storage.googleapi...](https://chromedriver.storage.googleapis.com/index.html)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:**  B|
|**Date (UTC):** 2020-11-01 15:54:22|**Time:** 00:00:03||

^(Created by [KoalaBear84's OpenDirectory Indexer](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

Screenshot  Link :  https://gofile.io/d/6Excfy

**Comment by KoalaBear84** [comment]
I see, at first it looks like it's just a regular apache index. Tried to scan it, and it indeed found nothing. So I looked at the source, and it's full javascript.

I'll try to look at it another time, to see if it can be implemented.

**Comment by M-Sethupathy** [comment]
Thanks for your effort

**Comment by KoalaBear84** [comment]
I did see that it is all in a S3 bucket. I've made an indexer for that in the past, might add support for that, but it comes at the cost of an extra library.

https://chromedriver.storage.googleapis.com/

**Comment by Chaphasilor** [comment]
Related: #76

**Comment by KoalaBear84** [comment]
Now supported with the url without index.html:
https://chromedriver.storage.googleapis.com/

Version building:
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.4.4.1
