### ISSUE TITLE
Console output should include "Created by KoalaBear84's OpenDirectory Indexer" banner

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#42]
**Is your feature request related to a problem? Please describe.**
Currently, the markdown table is printed to stdout, but it doesn't include the "Created by KoalaBear84's OpenDirectory Indexer" at the bottom. This sucks, because i want to credit you!

**Describe the solution you'd like**
Just print it out along the table. If people don't like it, they don't have to copy it. Alternatively, hide it behind a feature flag.

**Comment by KoalaBear84** [comment]
Yes, thanks, made some time for it :)

Released in version 1.7.0.3. Will be displayed in the final statistics.

https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.7.0.3
