### ISSUE TITLE
I Cannot Index Google Drives

### ISSUE THREAD

**Issue by everestokok** [KoalaBear84/OpenDirectoryDownloader#47]
I cannot Index This Shared Drive :

https://drive.google.com/drive/folders/154ylaZ34iTTVawSY5iNBVbVhoHewtWTX

It shows something like this

|**Url:** [https://drive.google.com/drive/folders...](https://drive.google.com/drive/folders/154ylaZ34iTTVawSY5iNBVbVhoHewtWTX)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:**  B|
|**Date (UTC):** 2020-11-23 20:18:52|**Time:** 00:00:03||

^(Created by [KoalaBear84's OpenDirectory Indexer](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

**Comment by KoalaBear84** [comment]
Is it a "Team Drive"? Is so, it will not work because it's only accessible behind credentials.

Don't know if it could be supported in the future.

**Comment by everestokok** [comment]
Main Link Is this : https://drive.google.com/drive/folders/1FEXQWN5szPBTau3EPFaC8PkOgp3v4cve
I didn't know if it is a "Team Drive" or not.

I didn't even know how to check if a shared drive is from "Team Drive" or not.

Is there anyway to check that?

**Comment by KoalaBear84** [comment]
Well.. I think somehow it is. Thanks for persisting in this, I added support for it 😇

Releasing a new version in couple of minutes.

**Comment by KoalaBear84** [comment]
Fixed in https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.0.0
