### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by Chaphasilor** [KoalaBear84/OpenDirectoryDownloader#48]
**Is your feature request related to a problem? Please describe.**

I'd like to integrate the indexer into my downloader server, so I can paste a "folder" url into my download manager and have it download all or a selection of all contained files.  
Given that that there are a ton of different OD html structures, it makes no sense to implement this myself when there's already a great solution out there!

Only problem: my download manager server runs on a Raspberry Pi 4, which uses an ARM architecture (armv6/7, 32 bit form what I've found). so the precompiled binaries won't work on the RP4.

**Describe the solution you'd like**

I already tried to compile the source myself, but I ran into some errors (sent you a message about it on reddit, but you never replied).  
I'm not familiar with .NET at all, so I'm having a hard time finding a solution.

That's why I'd like to ask if you could maybe provide precompiled ARM binaries as well?  
I imagine building for an additional platform isn't too hard if one knows what they are doing, and it would be greatly appreciated! :D

**Comment by KoalaBear84** [comment]
Hi @Chaphasilor

Hmm, I see. Recognized the message, but somehow never got back to it. It would be better if Reddit's messages was like a mailbox, and that you can archive messages, so always keep the ones you want to respond to.

I'll look into this, looks like there should be ARM support.

**Comment by KoalaBear84** [comment]
I've created a new build with "linux-arm64" which should work on Pi3+
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.0.2

Let me know if it works :)

**Comment by Chaphasilor** [comment]
Yeah, I suspected as much. Reddit's messaging is pretty flawed...

We need GitHub Messages! :D

**Comment by KoalaBear84** [comment]
See message above 😜

**Comment by Chaphasilor** [comment]
> See message above 😜

Oh damn that was fast 😳 

I was still replying and didn't see your reply xD 

I'll check it out tonight, but thanks in advance! :D

**Comment by Chaphasilor** [comment]
Hey @KoalaBear84, I just tried it out, but I'm afraid it doesn't work :/  

```shell
-bash: ./OpenDirectoryDownloader: cannot execute binary file: Exec format error
```

I'm suspecting this is due to the build being 64 bit, but my Debian being a 32 bit OS.  
Afaik there are only beta builds of 64 bit OSs for the Pi yet, so a 32 bit version should do the trick. These are often called armv6 or armv7 ([a bit more info here](https://www.raspberrypi.org/forums/viewtopic.php?t=245846#p1500898)).

Can you build for that architecture? If not, I could try setting up the .NET environment on my Pi :)

**Comment by KoalaBear84** [comment]
Ahh. Added `linux-arm`, might be 32-bit. Build will be ready in like 10 minutes.

**Comment by KoalaBear84** [comment]
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.0.9

**Comment by Chaphasilor** [comment]
![image](https://user-images.githubusercontent.com/18015147/100528239-cf91c300-31da-11eb-97da-d65005b294fa.png)

🥳🥳🥳

Thanks a lot!
It will be put to good use 😍

**Comment by KoalaBear84** [comment]
Great! 😁
