### ISSUE TITLE
High CPU usage after scan has finished

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#51]
**Describe the bug**
While waiting for the final keystore, ODD uses a lot of CPU.

**To Reproduce**
1. Run an OD scan
2. Wait for `Finished indexing!`
3. Check CPU usage

**Expected behavior**
ODD should be relatively idle. The loop to read the next keystroke (the only reasonable explanation) shouldn't consume as much CPU.

**Screenshots**

![image](https://user-images.githubusercontent.com/22377202/100586368-546e0100-32ef-11eb-9cf2-7314e4a14230.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.0.5
 - Version v1.9.1.0 self-contained

**Comment by KoalaBear84** [comment]
So I should remove the cryptominer?

**Comment by KoalaBear84** [comment]
Could be that you introduced it 😂

#44 

I'll look into it when I have time :)

**Comment by MCOfficer** [comment]
Looks like it :sweat_smile: I'm not sure if `Console.KeyAvailable` will still work if the key is pressed during the inevitable Thread.sleep (or whatever C#'s equivalent is).

**Comment by KoalaBear84** [comment]
I do not know either,

**Comment by MCOfficer** [comment]
It seems that this has ODD ignore the final keystroke on 1.9.2.0. Can you confirm that?

**Comment by KoalaBear84** [comment]
Hmm, could be. Currently no time, will try to check this afternoon.

**Comment by MCOfficer** [comment]
Hm, i can't reproduce this on my server... might've been an oddity with my terminal.

**Comment by KoalaBear84** [comment]
Reproducible?

**Comment by MCOfficer** [comment]
I've never encountered it since, so no.
