### ISSUE TITLE
Linux version is not executable by default

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#52]
**Describe the bug**

When extracting the current release's `self-contained` version, the file `OpenDirectoryDownloader` does not have an executable bit set. (I assume this is the same with the non-self-contained version).

**To Reproduce**
1. Download the current release to a linux machine
2. Extract using 7z, others should also work
3. Try to run ODD
4.
```
❯ ./OpenDirectoryDownloader --version                          
zsh: permission denied: ./OpenDirectoryDownloader 
```

**Expected behavior**
The zip should retain unix permissions.

This is likely because the build runs on windows, which can't retain unix permissions due to its own filesystem:

https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/39ebd32569559e9b53fff6b08cece3241f84f1b2/.github/workflows/main.yml#L13

If you want, i can improve the workflow to run on all OSs in parallel, which should also get rid of this issue.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.5
- Version: v1.9.1.0 self-contained, also happened with earlier versions.

**Comment by KoalaBear84** [comment]
Yes, tried to fix that on Saturday, but indeed didn't work. I guess I have to do move it into different jobs then and use artifacts on more places.. :)

**Comment by MCOfficer** [comment]
Unless i'm mistaken one can also get rid of a lot of duplicate code by running it in a matrix. Shall I try it?

**Comment by KoalaBear84** [comment]
Correct. It was like that [before](https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/6dcf58934bdbff0a78e0097fed7250967b1d9748/.github/workflows/main.yml), and at that time I didn't understand the artifacts thing completely to make it work.

There is one caveat, and that's the Linux x64 thing that will release a Docker Hub image that needs to still work.

**Comment by MCOfficer** [comment]
Do you have a better word for "non-self-contained", because this is kinda confusing.
![image](https://user-images.githubusercontent.com/22377202/100853923-a007e280-3488-11eb-8721-6b45e920ad80.png)

**Comment by KoalaBear84** [comment]
Normal? 😂

**Comment by MCOfficer** [comment]
hm. 
![image](https://user-images.githubusercontent.com/22377202/100855060-0d684300-348a-11eb-8f37-d035aa7d31fa.png)

normal it is  ¯\\_(ツ)_/¯

**Comment by KoalaBear84** [comment]
You are really doing a good job, nice to see you can do if statements in yaml, didn't have time to check all that before.

Ahh, I see already, when the first build and release finishes, it will immediately send a release email with only some files which are already uploaded.

So it needs to be a separate build job, and you can upload them all as artifacts. It will also append the commit text for every build as it seems.

![](https://user-images.githubusercontent.com/5886900/100857008-6c2ebc00-348c-11eb-9c58-f929507b0044.png)

**Comment by MCOfficer** [comment]
It's a bit of a hassle, but if that's an issue i can certainly do it. It's also a nice workaround for https://github.com/softprops/action-gh-release/issues/57.

**Comment by KoalaBear84** [comment]
Yes indeed, it would fix both issues.
