### ISSUE TITLE
Any way to get the Scanned URL from a URL file?

### ISSUE THREAD

**Issue by MCOfficer** [KoalaBear84/OpenDirectoryDownloader#53]
What the title says. Suppose i have a URL file, long after it has been scanned. Specifically, the scanned URL was `http://80s.lt/?dir=Files`.

The URL file only contains links like `http://80s.lt/Files/...`, which don't contain the original URL.

The filename is `http___80s.lt__dir=Files_.txt`, which i can't reliable infer the original URL from.

Is there any other fancy way you can think of?

**Comment by KoalaBear84** [comment]
No, there isn't a good way. Other than scanning `http://80s.lt/Files/` in this case 😃

The only other option is the JSON file, but when you don't have that, it could be complicated.

**Comment by MCOfficer** [comment]
I guess we'll just use JSONs instead.
