### ISSUE TITLE
Error with alx-xlx/goindex

### ISSUE THREAD

**Issue by iamhkr9** [KoalaBear84/OpenDirectoryDownloader#59]
2020-12-30 11:23:11.1330  [9] ERROR GoIndexParser.ScanIndexAsync Error processing GoIndex for URL: https://exclusive.getstudyfever5.workers.dev/0:/? ?????? ?? ??? , ? ????? ?? ?? ??????/@getstudyfever Atmanirbhar Bharat Android App Development/#/ System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenDirectoryDownloader.Site.GoIndex.GoIndexParser.ScanIndexAsync(HttpClient httpClient, WebDirectory webDirectory)

**Comment by KoalaBear84** [comment]
Wow, you just completely removed the whole Bug Report template..

Also you don't mention the correct credentials.

What are the current correct credentials?

**Comment by iamhkr9** [comment]
I am not able to download anything from this index https://exclusive.getstudyfever5.workers.dev/0:/%E0%A4%A8%20%E0%A4%B8%E0%A4%AE%E0%A5%8D%E0%A4%AE%E0%A4%BE%E0%A4%A8%20%E0%A4%95%E0%A4%BE%20%E0%A4%AE%E0%A5%8B%E0%A4%B9%20,%20%E0%A4%A8%20%E0%A4%85%E0%A4%AA%E0%A4%AE%E0%A4%BE%E0%A4%A8%20%E0%A4%95%E0%A4%BE%20%E0%A4%AD%E0%A4%AF%20%F0%9F%92%9E%F0%9F%92%AB%F0%9F%92%A5/@getstudyfever%20Atmanirbhar%20Bharat%20Android%20App%20Development/#
username:getstudyfever
Password:HAAMAIBHAKTHUOM

Can you help me with this ?

**Comment by iamhkr9** [comment]
here is the screenshot of my issue:
![image](https://user-images.githubusercontent.com/73501496/103334241-aa70c880-4a96-11eb-92f4-b5e2ccc88c62.png)

**Comment by KoalaBear84** [comment]
Please try new release:  
[https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.2.9](https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.2.9)

Be sure to call it with the `--username` and `--password` parameters

**Comment by iamhkr9** [comment]
thank you much now it's working superb.
