### ISSUE TITLE
Make sure logged filenames match the actual filenames 

### ISSUE THREAD

**Issue by Chaphasilor** [KoalaBear84/OpenDirectoryDownloader#64]
**Describe the bug**

When scanning a url with uncommon characters (like Chinese Hanzi), the filename logged to the console differs from the actual filename.

**To Reproduce**

1. Scan `https://pan.gou13.cn/%E7%A6%BB%E7%BA%BF%E4%B8%8B%E8%BD%BD` (with flag `-j`)
2. ODD will log `Saved URL list to file: https___pan.gou13.cn_????_.txt` and `Saved session: https___pan.gou13.cn_????_.json`
3. The actual filenames (at least on Windows) are: `https___pan.gou13.cn_离线下载_.txt` and `https___pan.gou13.cn_离线下载_.json`

**Expected behavior**

The output in the console should (at least if the terminal/tty supports it) always match the actual filenames.  
This might be achieved by setting the encoding of the process' `stdout` to `utf8`.  
I already tried setting the encoding of the output stream when reading it in, but my guess is that at that point the character encoding is already lost irrevocably.

**Screenshots**

![image](https://user-images.githubusercontent.com/18015147/105645752-f77c6a80-5e9b-11eb-87c3-7299ce90cf52.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v1.9.3.3
 
---

Related to this:  
Normally there would be an easy workaround for this, by using the `--output-file` flag.  
The problem here is that the flag only applies to the "urls file" (the `.txt` file). If this would also apply to any other file saved by ODD (like the `.json` file), like it *should* be, then I could've worked around this bug.  
For now though I have no other option than filing this bug report ://

**Comment by KoalaBear84** [comment]
I didn't notice that the filename weren't in sync. For now that workaround :)

It now displays the full filename, be aware of that.

[https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.3.4](https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.3.4)

I've been down the UTF8 console thing before, but now there are more options/terminals (on Windows) which supports this I might try that again.

**Comment by KoalaBear84** [comment]
I'll create a new ticket for UTF8.

**Comment by Chaphasilor** [comment]
I knew I could count on you \^\^  
Thanks a ton!

**Comment by Chaphasilor** [comment]
> `Saving URL list to file..`

Sooo, why did you remove one dot at the end? xD  
(Now please don't add it back in, unless you reaaaally want to 😅)

But, I can definitely confirm this works :)

**Comment by KoalaBear84** [comment]
You got me! Sorry, had to use 2 only, and everywhere 😇👍
