### ISSUE TITLE
Support UTF-8 output in console/terminal

### ISSUE THREAD

**Issue by KoalaBear84** [KoalaBear84/OpenDirectoryDownloader#65]
**Is your feature request related to a problem? Please describe.**  
Support UTF-8

**Describe the solution you'd like**  
Support UTF-8

Continuation of #64

**Comment by KoalaBear84** [comment]
@[Chaphasilor](https://github.com/Chaphasilor)

Fixed in 1.9.3.6, tested in Windows Terminal. In "Command Prompt" it will get 'worse', well, the "?" will be replace with a square in a box and an extra space.

https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.3.6

![](https://user-images.githubusercontent.com/5886900/105702934-cd16c580-5f0c-11eb-952b-a15558505805.png)

**Comment by Chaphasilor** [comment]
Oh sorry didn't get the mention 😅

Yep, Terminal works and using the processes `stdout` works as well! ty <3

**Comment by KoalaBear84** [comment]
Great!
