### ISSUE TITLE
Please this notebook of this project so i can use it in google colab 

### ISSUE THREAD

**Issue by imhkr** [KoalaBear84/OpenDirectoryDownloader#66]
Please this notebook of this project so i can use it in google colab.
Please make it like that we can use it in google colab.

**Comment by KoalaBear84** [comment]
Hi, see #31 

I have no knowledge about it, also limited in time.

But if anyone can provide it, I can add it to the repository or maybe help in another way.

**Comment by imhkr** [comment]
This may help https://github.com/M-Sethupathy/OpenDirectoryDownloader-Colab

**Comment by Chaphasilor** [comment]
Maybe @M-Sethupathy could update his notebook? It's already done, but it could use a more recent version :)
