### ISSUE TITLE
Automatically copy to clipboard

### ISSUE THREAD

**Issue by everestokok** [KoalaBear84/OpenDirectoryDownloader#68]
After scanning an OD, I need to press "C" to copy Reddit Markdown to clipboard.

Is there anyway to automate the process of "Copy to clipboard automatically"?

Needed for my python script :)

**Comment by KoalaBear84** [comment]
Currently there is not. Currently too busy, but could check when I have some time.

**Comment by everestokok** [comment]
Do as you please :)

**Comment by Chaphasilor** [comment]
@KoalaBear84 I would like to create a PR for this. Could you tell me how to cross-compile for Windows from linux, so I can test it? 😅

**Comment by KoalaBear84** [comment]
When I saw the mail and read (only) the body of the mail I thought about a different issue 😅

The whole build thing is in the [GitHub workflow](https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/master/.github/workflows/main.yml)

Boils down to:

```
dotnet publish OpenDirectoryDownloader --configuration Release -p:Version=1.2.3.4 --framework net5.0 --runtime win-x64 --self-contained=true -p:PublishSingleFile=true --output ./OpenDirectoryDownloader-win-x64
dotnet publish OpenDirectoryDownloader --configuration Release -p:Version=1.2.3.4 --framework net5.0 --runtime linux-x64 --self-contained=true -p:PublishSingleFile=true --output ./OpenDirectoryDownloader-linux-x64
```

I'm done with the mandatory work 😅

For this issue, I can add it in a couple of minutes. So I could do it as well.

**Comment by Chaphasilor** [comment]
> For this issue, I can add it in a couple of minutes. So I could do it as well.

Let me try it 😇  
If I'm missing something or you aren't happy with it, you can give me some feedback as to what I can improve next time and then merge your own changes (faster than leaving a review and waiting for me to get it right 😂)

**Comment by KoalaBear84** [comment]
Yes, very good! Always good to learn. I always find it different, the PR part, I mean as a supplier of the PR, the workflow. But I did that before, long time ago.

Go ahead! 👍

**Comment by Chaphasilor** [comment]
Here you go @everestokok <3

**Comment by KoalaBear84** [comment]
Thanks @Chaphasilor 

Released: https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.3.7

**Comment by everestokok** [comment]
Thanks to Both of you @Chaphasilor & @KoalaBear84 :)
