### ISSUE TITLE
alx-xlx / goindex not working

### ISSUE THREAD

**Issue by kappaWide** [KoalaBear84/OpenDirectoryDownloader#71]
**Describe the bug**
alx-xlx / goindex not working in v1.9.3.8

**To Reproduce**
1.` ./OpenDirectoryDownloader --url "https://dark.getstudyfever11092.workers.dev/0:/Exclusive%20Drive/NC%20COOLiE%20No.1%20P/" --username "getstudyfever" --password "HAAMAIBHAKTHUOM"
`
**Error**
```
Error. Invalid response. Stopping.
2021-02-02 08:46:31.9113  [5] ERROR Go2IndexParser.ParseIndex Error. Invalid response. Stopping. 
Finshed indexing
```

**Comment by KoalaBear84** [comment]
Currently cannot test it because the index itself is broken.

![](https://user-images.githubusercontent.com/5886900/106615904-392ca580-656d-11eb-8bef-984923ed58a3.png)

Let me know when it is working again.

**Comment by kappaWide** [comment]
Index is backup as of now, although URL has slightly changed
`./OpenDirectoryDownloader --url "https://dark.getstudyfever11092.workers.dev/0:/VIKAS%20KA%20TAALA%20SANJU%20LALA/Exclusive%20Drive/BC%20Dynamic%20Programming%20/" --username "getstudyfever" --password "HAAMAIBHAKTHUOM"`

Backup URLs with same login details
```
https://dark.getstudyfever4.workers.dev/0:/
https://dark.getstudyfever3.workers.dev/0:/
https://dark.getstudyfever2.workers.dev/0:/
https://dark.getstudyfever11092.workers.dev/0:/
```

**Comment by KoalaBear84** [comment]
I see. I also see it is working with the command line parameters.

The first time it didn't, that's the only catch.. If the first request fails it will stop, if the first request works it will retry for the other calls.

Also works over there?

**Comment by kappaWide** [comment]
Results are very varied for me. Sometime its does not index a single file, sometimes its as you mentioned "If the first request fails it will stop, if the first request works it will retry for the other calls." Its first time I am having this issues,  I have successfully used OOD to index same index many times in past

**Comment by KoalaBear84** [comment]
I don't know what we can do about it, if the input is 'flaky' then the output will also be.
