### ISSUE TITLE
Does not work with Fancy IIS

### ISSUE THREAD

**Issue by a8underscore** [KoalaBear84/OpenDirectoryDownloader#75]
**Describe the bug**
hello it doesnt work with "https://files.z14n.com/Documents/Books/70%20Books%20by%20Stephen%20King/SK-70%20Books/" it shows output such as following
```
|**Url:** [https://files.z14n.com/Documents/Books...](https://files.z14n.com/Documents/Books/70 Books by Stephen King/SK-70 Books/)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 282 **Ext:** 0|**Total:** 0|**Total:**  B|
|**Date (UTC):** 2021-02-21 03:42:38|**Time:** 00:08:25||

^(Created by [KoalaBear84's OpenDirectory Indexer](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

```

**Desktop (please complete the following information):**
 - OS: [e.g. Arch linux]
 - Version: [v1.9.3.8]

**Comment by KoalaBear84** [comment]
Damn. So it's a custom index, that's OK, the problem is that it does not have a nice/logic structure. I've tried to fix it, but somehow I can't get it to correctly detect the structure. Need to look at it again, but not sure when I have time. :|

https://www.z14n.com/Portfolio/#FancyIndexing_for_IIS

**Comment by Chaphasilor** [comment]
If you can't figure it out, I can give it a try as well :)

**Comment by KoalaBear84** [comment]
It would be much appreciated. Good to get more experience. Don't break a leg 😀

**Comment by Chaphasilor** [comment]
OD seems to be dead now, but luckily I grabbed a few samples a while ago:

[Fancy IIS.zip](https://github.com/KoalaBear84/OpenDirectoryDownloader/files/6918403/Fancy.IIS.zip)

`subdir.html` was saved using the browser and includes stylesheets, etc.  
`subdir_curl.html` was recorded using `curl`.
