### ISSUE TITLE
Does not work with JavaScript generated (S3)

### ISSUE THREAD

**Issue by mujtabaxd** [KoalaBear84/OpenDirectoryDownloader#76]
I tried to run this website but it's not working. It returned this error: 
```
Finshed indexing
|**Url:** [http://dl.ncsbe.gov.s3.amazonaws.com/i...](http://dl.ncsbe.gov.s3.amazonaws.com/index.html?prefix=)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:**  B|
|**Date (UTC):** 2021-02-22 08:38:06|**Time:** 00:00:04||

^(Created by [KoalaBear84's OpenDirectory Indexer](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

No URLs to save
Http status codes
200: 1
Total files: 0, Total estimated size:  B
Total directories: 1
Total HTTP requests: 1, Total HTTP traffic: 520 B
|**Url:** [http://dl.ncsbe.gov.s3.amazonaws.com/i...](http://dl.ncsbe.gov.s3.amazonaws.com/index.html?prefix=)|||
|:-|-:|-:|
|**Extension (Top 5)**|**Files**|**Size**|
|**Dirs:** 1 **Ext:** 0|**Total:** 0|**Total:**  B|
|**Date (UTC):** 2021-02-22 08:38:06|**Time:** 00:00:04||

^(Created by [KoalaBear84's OpenDirectory Indexer](https://github.com/KoalaBear84/OpenDirectoryDownloader/))

Finished indexing!
Press ESC to exit! Or C to copy to clipboard and quit!
```
 - OS: [Windows 10]
 - Version: [ v1.9.3.8]

**Comment by KoalaBear84** [comment]
I've encountered this one before. Generated through JavaScript. Will try to support it, not sure when I have time to look at it.

**Comment by mujtabaxd** [comment]
Does this tool has selenium support?

**Comment by mujtabaxd** [comment]
Does this tool has selenium support?

**Comment by mujtabaxd** [comment]
Does this tool have selenium support?

**Comment by KoalaBear84** [comment]
No, it only retrieves the HTML and parses it. And for some formats it emulates the 'AJAX' / javascript calls.

**Comment by KoalaBear84** [comment]
Better late then never? Implemented it. Thanks to @Chaphasilor for giving a little push to fix his issue and got wandering 😂

Supports at least the following urls:
http://dl.ncsbe.gov.s3.amazonaws.com/
http://dl.ncsbe.gov.s3.amazonaws.com/index.html
http://dl.ncsbe.gov.s3.amazonaws.com/index.html?prefix=
http://dl.ncsbe.gov.s3.amazonaws.com/index.html?prefix=Voter_Registration/

It's released:
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.3.1.4
