### ISSUE TITLE
Support for JavaScript

### ISSUE THREAD

**Issue by KoalaBear84** [KoalaBear84/OpenDirectoryDownloader#77]
**Is your feature request related to a problem? Please describe.**
Try to support directories 'build' or protected with JavaScript. I know Cloudflare also protects things with JavaScript, but I'm not talking about that, if so, it should be another ticket, but it's not that trivial.

The site in this case is: http://mbonwick.byethost7.com/SCNW/Fleetcards/?dir=./

**Describe the solution you'd like**
I would like to add support for it, but the checks might be 'hard' or specific. Not sure about the best way yet. Or there must be a C# library which can support JavaScript, or we need a FULL Chromium browser to do it. We can use https://github.com/hardkoded/puppeteer-sharp for this.

The problem is that the multithreaded part has to go/disabled. Or we have to sometimes use cookies from the Chromium browser and 'transfer' them to the C# CookieContainer and use that in the HttpClient.

**Comment by KoalaBear84** [comment]
For the mentioned website this is the example:

```html

<html>
  <body>
    <script type="text/javascript" src="/aes.js"></script>
    <script>
      function toNumbers(d) {
              var e = [];
              d.replace(/(..)/g,
                  function (d) { e.push(parseInt(d, 16)) });
              return e
          }
          function toHex() {
              for (var d = [], d = 1 == arguments.length && arguments[0].constructor == Array ? arguments[0] : arguments, e = "", f = 0; f < d.length; f++)
                  e += (16 > d[f] ? "0" : "") + d[f].toString(16);
              return e.toLowerCase()
          }
          var a = toNumbers("f655ba9d09a112d4968c63579db590b4"),
              b = toNumbers("98344c2eee86c3994890592585b49f80"),
              c = toNumbers("59e9b5f115d1b806473c6710d327ff97");
          document.cookie = "__test=" + toHex(slowAES.decrypt(c, 2, a, b)) + "; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";
          location.href = "http://mbonwick.byethost7.com/SCNW/Fleetcards/?i=1";
    </script>
    <noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support
    </noscript>
  </body>
</html>
```

**Comment by Chaphasilor** [comment]
What if we simply use `puppeteer-sharp` to make the `GET` requests, instead of `HttpClient`, and then use the returned HTML to parse the OD?  
We can probably disable external resources (like other js files or CSS), so that the page should load relatively quick.

**Comment by KoalaBear84** [comment]
I know that is possible, but we should not do that. It would kill everything it is made for. Speed, memory usage, no multi threaded.

We should really use it for edge cases like this. But we should be able to detect when it is needed. Could be hard sometimes. And maybe eventually we could show the browser when a Cloudflare captcha is shown or something like that.

**Comment by Chaphasilor** [comment]
Hmm, I see. I'm wondering, why would using puppeteer prevent multi-threading?

About the edge-case stuff, we could handle this the same way as the "retrying with a different user agent". If we get strange results (403s or empty dirs), we retry with the browser, check if if improves the results and then re-use the cookies.  
(This might also solve the CF problem)

**Comment by KoalaBear84** [comment]
You don't want X Chromium browsers/tabs all at once. It's a LOT more CPU/memory intensive comparing to just download HTML and parse it with a good engine.

**Comment by Chaphasilor** [comment]
Got it.

So what about my proposal? 🤔

**Comment by KoalaBear84** [comment]
Yes. Need to think about it what would be best, and test some things out.

**Comment by KoalaBear84** [comment]
Another example of drawn by JavaScript:

https://149.56.222.150/

**Comment by Chaphasilor** [comment]
> https://149.56.222.150/

This one is really strange 👀  
I guess RegEx is the best solution for this one.

I'm not sure yet how generic you want the support to be, do you want to detect any OD that requires JS to work?  
Or just specific, hard-coded formats?

**Comment by KoalaBear84** [comment]
See https://github.com/KoalaBear84/OpenDirectoryDownloader/commit/5c6df605192ffb15f29a49368a06b890ce14c382 😀

**Comment by Chaphasilor** [comment]
> See https://github.com/KoalaBear84/OpenDirectoryDownloader/commit/5c6df605192ffb15f29a49368a06b890ce14c382 😀

huh, neat.  
I really need to familliarize myself more with the code base, I still don't fully grasp how you detect the format/which parser to use...

**Comment by KoalaBear84** [comment]
In general it goes from very specific to less specific. It's not that complex luckily. At first glance it off course might be.

**Comment by Chaphasilor** [comment]
> See [5c6df60](https://github.com/KoalaBear84/OpenDirectoryDownloader/commit/5c6df605192ffb15f29a49368a06b890ce14c382)

![image](https://user-images.githubusercontent.com/18015147/110019672-05d66580-7d29-11eb-9c3a-27e19da5dbbc.png)
should I fix this? working on the file right now anyway...

**Comment by KoalaBear84** [comment]
You can. I always leave it 🙈🍺

**Comment by KoalaBear84** [comment]
Also see #76 

But that one might be possible to 'detect' and do the requests.

**Comment by KoalaBear84** [comment]
This one is now implemented for the example in the first comment. It is done through starting a Chromium browser.

**Comment by KoalaBear84** [comment]
Accidently did 2.4.4.0 I see instead of 2.4.0.0.. 😬 Oh well.. 😂
https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v2.4.4.0

**Comment by KoalaBear84** [comment]
They must have seen it, because now it's gone! @Chaphasilor noticed it was gone. We must have scared them 😂
