### ISSUE TITLE
Improve Speedtest information

### ISSUE THREAD

**Issue by Chaphasilor** [KoalaBear84/OpenDirectoryDownloader#79]
**Describe the bug**

The speed test reports a download speed of "0 MB/s", even though the actual speed is somewhere around 0.2 MB/s.

**To Reproduce**
1. Scan 'http://dl.kartoonet.com/' with the `-s` flag

**Expected behavior**

Speed test should report ~0.2 MB/s

**Desktop (please complete the following information):**
Probably platform-independent

**Comment by Chaphasilor** [comment]
The OD's dead, but essentially this issue is about making the speedtest more reliable for slower ODs with smaller files.  
Could be done by e.g. using multiple files for the test, if the individual files are too small.

**Comment by KoalaBear84** [comment]
We discussed this might be solved with doing a HEAD request before the real speedtest.

**Comment by KoalaBear84** [comment]
Looks like this was already in place. We discussed this again 'lately'. So the connection is already 'open' / 'hot'

**Comment by Chaphasilor** [comment]
So there's nothing to do?

I guess *something* isn't working reliably, or this issue wouldn't exist 🤔

**Comment by KoalaBear84** [comment]
Do you have some examples? Or things we can try?

**Comment by Chaphasilor** [comment]
Not off of the top of my head...

I'll keep my eyes peeled!

**Comment by Chaphasilor** [comment]
Found a new example: `https://joniaustinddlq.firebaseapp.com/`

![image](https://user-images.githubusercontent.com/18015147/127894803-3db044ec-72c5-4837-935b-ec133d511951.png)

Speedtest results in `0.0 MB/s (0 mbit)`. I've seen scans before that had `0.1 MB/s (0 mbit)`, so maybe this is just an issue with rounding and we just have to add another decimal place?

Interestingly it's not a true OD and the reported file sizes don't correspond to the sizes of the actual linked files. Which is confusing, because I would've thought in that case the speed would be much higher instead of lower...  
However, the size used for calculating the speed if probably based on the `Content-Size` header returned with the `GET` request, so this shouldn't matter at all.

Here's what `wget` says about the speed:

![image](https://user-images.githubusercontent.com/18015147/127895092-57ccbb4f-9e82-4052-8351-455c2e563015.png)

**Comment by KoalaBear84** [comment]
OK, yes, this is not really an issue. It could be improved to at least show a digit which is not 0. Can also change to kB/s when it doesn't even get 0.1MB/s.

It's also a problem if the file is only some kB/s, you'll never get a great speed test for that.

And yes, the speedtest is based on what is really downloaded, so that's not an issue.
