### ISSUE TITLE
It always count less files then total file in directory 

### ISSUE THREAD

**Issue by imhkr** [KoalaBear84/OpenDirectoryDownloader#82]
**Describe the bug**
It always count less files then total file in directory  for eg. if there is 59 files then it's count only 58  files as total no. of files.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 1.0.0.0]

**Comment by KoalaBear84** [comment]
This is not clear. I need very specific example(s).

**Comment by Chaphasilor** [comment]
@imhkr could you provide us with an URL where this is the case? :)
