### ISSUE TITLE
Json file downloder

### ISSUE THREAD

**Issue by Koala-Bear1** [KoalaBear84/OpenDirectoryDownloader#83]
How to download file from gdrive to which we have created json files?

**Comment by Chaphasilor** [comment]
Currently, downloading isn't implemented. The tool is just for getting the links.

So try looking for a "Google Drive (Batch) Downloader" and see if you can paste the URLs there :)

**Comment by KoalaBear84** [comment]
Hi fellow Koala-Bear 😂

Good question, never tried that. Some people might have figured this out in linux with the jq command:  
[https://stedolan.github.io/jq/](https://stedolan.github.io/jq/)

But I have no idea what would be the best approach for Google Drive.

Hopefully one of the users can answer this. Looks like @Chaphasilor already gave some directions. Let us know if you succeed 👍

**Comment by Koala-Bear1** [comment]
I was trying to download the txt file links with wget, aria2c, and many but while doing the indexex most of the time i am getting internal server error

**Comment by Chaphasilor** [comment]
You are getting `Internal Error` messages in the output of OpenDirectoryDownloader?

**Comment by Koala-Bear1** [comment]
No.....I am getting this error while using wget to download files.... please tell any other tools to download files from .txt list

**Comment by Chaphasilor** [comment]
Try this: https://github.com/haindvn/GDrive-Folder-Downloader  
or this: https://github.com/YuuDrive/google-drive-batch-downloader  
You won't need the `.txt` file generated by ODD for those tools...

However, your issue is not related to this project, it seems :)

**Comment by KoalaBear84** [comment]
I think it is indeed better to use Google Drive specific downloading tools.
