### ISSUE TITLE
Not working on this index

### ISSUE THREAD

**Issue by imhkr** [KoalaBear84/OpenDirectoryDownloader#85]
Your script is not working on this index.
https://sf.miret67625.workers.dev/0:/

![image](https://user-images.githubusercontent.com/55655793/113482484-933dde80-94bc-11eb-92a9-c81adb775639.png)

**Comment by KoalaBear84** [comment]
Can't check it without the right credentials.

**Comment by ZafarAqil** [comment]
@KoalaBear84 is there any way people can contact you via email?

**Comment by KoalaBear84** [comment]
Currently not, do not have a public email. But you can contact me on Reddit with a PM.

**Comment by ZafarAqil** [comment]
@KoalaBear84 I have sent a DM to u/KoalaBear84/ pls check :)

**Comment by KoalaBear84** [comment]
@ZafarAqil Hmm, could you send it again, can't seem to find it (anymore).

**Comment by ZafarAqil** [comment]
@KoalaBear84 the issue got fixed after the latest update at that time

**Comment by KoalaBear84** [comment]
OK, great, then this can be closed 👍
