### ISSUE TITLE
Not working on this google drive index

### ISSUE THREAD

**Issue by shsagnik** [KoalaBear84/OpenDirectoryDownloader#86]
**Describe the bug**
using the program on this link produces "https://sf.piyoba9413.workers.dev/1:/VIKAS%20KA%20PAHIYA%20GAMMA%20BHAIYA/Courses%20and%20Placement%20Material%20-%20CS%20and%20IT/" with provided username and password respectively being "@getstudyfever" and "agni" produces the error 

Started with PID 7090
URL specified: “https://sf.piyoba9413.workers.dev/1:/VIKAS%20KA%20PAHIYA%20GAMMA%20BHAIYA/Courses%20and%20Placement%20Material%20-%20CS%20and%20IT/”
Unhandled exception. System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at OpenDirectoryDownloader.Library.FixUrl(String url)
   at OpenDirectoryDownloader.Program.Main(String[] args)
   at OpenDirectoryDownloader.Program.<Main>(String[] args)
zsh: abort       --url  --username “@getstudyfever” --password “agni”  

**To Reproduce**

OpenDirectoryDownloader --url “https://sf.piyoba9413.workers.dev/1:/VIKAS%20KA%20PAHIYA%20GAMMA%20BHAIYA/Courses%20and%20Placement%20Material%20-%20CS%20and%20IT/” --username “@getstudyfever” --password “agni” --output-file “urllist”

![Screen Shot 2021-04-07 at 1 47 49 AM](https://user-images.githubusercontent.com/42864237/113773159-43bd1400-9743-11eb-839c-da5bc0de3458.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS BigSur 11.2.2]
 - Version: [e.g. 1.9.6.0]

**Comment by KoalaBear84** [comment]
It looks like it is because of the 'wrong' quotes. “ and ” instead of ".

![](https://user-images.githubusercontent.com/5886900/113774605-c9cb6180-9727-11eb-9a37-de987c7e303c.png)

**Comment by shsagnik** [comment]
Thanks for the quick reply and sorry for the stupid error, I didn't even know till now that there are two types of quotes
thanks again

**Comment by KoalaBear84** [comment]
No problem. Also had to look twice 👍😂

**Comment by Chaphasilor** [comment]
> `OpenDirectoryDownloader --url “https://sf.piyoba9413.workers.dev/1:/VIKAS%20KA%20PAHIYA%20GAMMA%20BHAIYA/Courses%20and%20Placement%20Material%20-%20CS%20and%20IT/”` 

wrong quotes here as well (look how the quote at the end of the URL is marked as part of the URL)
