### ISSUE TITLE
Paging support

### ISSUE THREAD

**Issue by KoalaBear84** [KoalaBear84/OpenDirectoryDownloader#9]
Some directory listings have paging, implement a generic way to support this

**Comment by Chaphasilor** [comment]
Example links would be nice \^\^

**Comment by KoalaBear84** [comment]
Indeed. Sadly my example is gone 😂

https://www.reddit.com/r/opendirectories/comments/ap1k0p/jav_s_speed/

**Comment by KoalaBear84** [comment]
Most specific implementations already have paging support, but it's in the specific parser itself. Currently don't have an example of a generic directory listing which has pages.
