### ISSUE TITLE
Not working on this index (user/pass included)

### ISSUE THREAD

**Issue by shsagnik** [KoalaBear84/OpenDirectoryDownloader#90]
**Describe the bug**
hi koala! So I want to make a bug report
So basically the indexer isnt working on this index

https://resources.teleflix.workers.dev/1:/SF%20V2/Vikas%20Ka%20Pahiya/[MISCALLANEOUS]/[BHARAT%20ACHARYA]/
username is blank
password is @ttu001
I am on the OpenDirectoryDownloader v1.9.6.4 which currently is the latest and I have tried both ways, once using the all the args and once not including the username arg cuz it is supposed to be left blank

![Screen Shot 2021-06-01 at 12 34 15 AM](https://user-images.githubusercontent.com/42864237/120232388-1ab38e00-c271-11eb-9163-ee3e7aa04bf1.png)

**Desktop
 - OS: BigSur 11.4

**Comment by KoalaBear84** [comment]
Hmm, I see that username cannot be blank if you want a password, that's an easy fix.

But what isn't an easy fix, is the part that the response is heavily encoded/encrypted through a pack of JavaScript. 😶

**Comment by KoalaBear84** [comment]
I've managed to implement this, thanks to Jint.

https://github.com/KoalaBear84/OpenDirectoryDownloader/releases/tag/v1.9.7.1

**Comment by KoalaBear84** [comment]
Let me know if it works (or not)!

**Comment by shsagnik** [comment]
Thanks for the fix koala! I will test it out in a while and let you know,
THANK YOU!!

**Comment by shsagnik** [comment]
Yes Koala it is working now plus I see that it is a lot faster now when it
comes to indexing

Thanks a lot man

**Comment by KoalaBear84** [comment]
Great 👍
