### ISSUE TITLE
Honor 429 response from HTTP

### ISSUE THREAD

**Issue by vijayanandnandam** [KoalaBear84/OpenDirectoryDownloader#91]
**Is your feature request related to a problem? Please describe.**
When i was checking the-eye.eu/public, the downloaded is not handling request limiting by server
```
2021-06-10 07:18:30.6506 [12]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Queue: 481,575, Queue (filesizes): 0
2021-06-10 07:19:00.8223 [17]  WARN OpenDirectoryIndexer.TimerStatistics_Elapsed Http status codes
200: 16492
429: 18428
Total files: 914,612, Total estimated size: 10.58 TiB
Total directories: 34,944
Total HTTP requests: 34,952, Total HTTP traffic: 432.09 MiB
|**Url:** https://the-eye.eu/public/|||
|:-|-:|-:|
|**Date (UTC):** 2021-06-10 06:58:59|**Time:** 00:20:00||
```
This leads to missing many of files being indexed

**Describe the solution you'd like**
Usually 429 http response from a server is not a fatal error. The http client should honor 429,  pause the crawling activity and retry the errored urls with http code 429

**Comment by vijayanandnandam** [comment]
Seems like you are handling it here.. closing this. sorry for the noise
https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/fad9119d8e9742dcaccf2e46862910a0622866d1/src/OpenDirectoryDownloader/OpenDirectoryIndexer.cs#L72

**Comment by KoalaBear84** [comment]
It's no problem. It does handle it as it should, but I hope it's not going to the line you mentioned, but to this one, where it waits as the server tells it to:

https://github.com/KoalaBear84/OpenDirectoryDownloader/blob/fad9119d8e9742dcaccf2e46862910a0622866d1/src/OpenDirectoryDownloader/OpenDirectoryIndexer.cs#L900
