### ISSUE TITLE
Make the URL in markdown stats more reliable

### ISSUE THREAD

**Issue by Chaphasilor** [KoalaBear84/OpenDirectoryDownloader#97]
**Describe the bug**

Sometimes, URLs are weird, with strange characters or spaces in-between. Most URL-parsers break down, causing the link at the top of the reddit results to not be detected correctly / clickable.

**To Reproduce**

1. Scan any URL with a space, e.g. `http://173.49.87.32:8080/3DS CIA's/`
2. Paste the markdown on Reddit and look at the parsed URL or try to click it.

**Expected behavior**

Clicking the URL at the top should always send you to the actual linked OD, special characters or not.

**Desktop (please complete the following information):**
 - Platform-independent
 
 **Proposed solution**
 
 Wrap the URL in a markdown link, like `[<url>](<url>)`. This makes sure that the link works as it's supposed to work.  
 
 PS: I'll gladly fix this myself in the coming days, unless you are bored \^\^

**Comment by KoalaBear84** [comment]
You can fix it, that would be nice 👍
