### ISSUE TITLE
Indexing the-eye.eu with "--exact-file-sizes" results is file sizes determined as 0

### ISSUE THREAD

**Issue by ericziethen** [KoalaBear84/OpenDirectoryDownloader#99]
**Describe the bug**
When trying to index the directories in "the-eye.eu" ad storing the result as json, multiple "FileSize" attributes are set to 0.
When running the same command again the same happens but a different set of files will be affected.

**To Reproduce**
1. Use OpenDirectoryDownloader v2.0.0.5
2. run commnd: 'OpenDirectoryDownloader.exe --url "https://the-eye.eu/public/Comics/DC%20Chronology/DC%20Comics%20Chronology%202005/09-Sept/" --quit --json --exact-file-sizes --output-file dc_2005_09_09'
3. Check created json file "dc_2005_09_09.json"
4. See that multiple file sizes are set to 0

**Expected behavior**
All file sizes should be populated

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v2.0.0.5
[dc_2005_09_09.txt](https://github.com/KoalaBear84/OpenDirectoryDownloader/files/7006669/dc_2005_09_09.txt)
[OpenDirectoryDownloader.log](https://github.com/KoalaBear84/OpenDirectoryDownloader/files/7006670/OpenDirectoryDownloader.log)

**Comment by Chaphasilor** [comment]
Hmm, that's strange. I'll look into it soon!

Meanwhile, what happens if you leave out the `--exact-file-sizes` flag? I think theEye reports file sizes in HTML (not sure though)

**Comment by ericziethen** [comment]
In that case the HTML sizes are all there. The only down size with that is that they are not as accurate so for example they couldn't be used to compare with actual file sizes.

**Comment by Chaphasilor** [comment]
The problem was that ODD made too many requests too quickly and The Eye kind of rate limited it by not returning the `Content-Length` header anymore. This wasn't handled well and ODD didn't retry the request...

Should be fixed as soon as @KoalaBear84 approves & merges the PR and releases a new version 😇
